# Generated by Django 6.1.1 on 2026-09-30 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0002_basicuserinfomodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('basicuserinfomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authApp.basicuserinfomodel')),
                ('id_no', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/teacher_img')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('authApp.basicuserinfomodel',),
        ),
    ]
