# Generated by Django 6.1.1 on 2026-09-30 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_coursemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_credit',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
